import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { assignEventTeamMember, cancelEvent, completeEvent, publishEvent, removeEventTeamMember, updateDraftEvent } from "../actions";

const labels: Record<string, string> = { draft: "مسودة", published: "منشورة", completed: "مكتملة", cancelled: "ملغاة", registered: "مسجل", attended: "حضر", absent: "غاب", cancelled_registration: "ألغى التسجيل" };
const errors: Record<string, string> = { "invalid-event": "راجع بيانات الفعالية.", "update-failed": "تعذر حفظ التعديل.", "publish-failed": "تعذر النشر. يجب أن تكون الفعالية مسودة مستقبلية داخل موسم نشط.", "cancel-failed": "تعذر الإلغاء.", "invalid-team": "راجع العضو والمسمى.", "team-failed": "تعذر تحديث الفريق.", "invalid-attendance": "راجع حالات الحضور.", "complete-failed": "تعذر إتمام الفعالية. يجب تسجيل كل القائمة النشطة." };
const success: Record<string, string> = { updated: "تم حفظ المسودة.", published: "نُشرت الفعالية والرابط العام جاهز.", cancelled: "أُلغيت الفعالية.", "team-updated": "تم تحديث فريق الفعالية.", completed: "تم تسجيل الحضور وإتمام الفعالية." };

type Event = { event_id: string; season_name: string; season_status: string; title: string; objective: string | null; starts_at: string; ends_at: string; venue: string | null; capacity: number | null; status: string; registration_count: number | null; my_team_role: string | null };
type Member = { user_id: string; display_name: string };
type Team = { membership_id: string; user_id: string; display_name: string; role_title: string; assigned_at: string };
type Registration = { registration_id: string; user_id: string; display_name: string; registration_status: string; registered_at: string };

function inputDateTime(value: string) { return new Intl.DateTimeFormat("sv-SE", { timeZone: "Africa/Cairo", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value)).replace(" ", "T"); }
function formatDateTime(value: string) { return new Date(value).toLocaleString("ar-EG", { timeZone: "Africa/Cairo", dateStyle: "medium", timeStyle: "short" }); }

export default async function EventDetailPage({ params, searchParams }: { params: Promise<{ organizationId: string; eventId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { organizationId, eventId } = await params; const query = await searchParams; const supabase = await createClient(); const { data: auth } = await supabase.auth.getClaims();
  if (!auth?.claims?.sub) redirect("/auth"); const userId = String(auth.claims.sub);
  const [membershipResult, eventsResult] = await Promise.all([
    supabase.from("memberships").select("role, status").eq("organization_id", organizationId).eq("user_id", userId).maybeSingle(),
    supabase.rpc("list_events", { p_organization_id: organizationId }),
  ]);
  if (membershipResult.error || eventsResult.error) throw new Error("Failed to load event");
  if (membershipResult.data?.status !== "active") notFound();
  const manager = ["owner", "board", "head"].includes(membershipResult.data.role);
  const event = ((eventsResult.data as Event[] | null) ?? []).find((item) => item.event_id === eventId);
  if (!event) notFound();
  const [directoryResult, teamResult, registrationsResult] = manager ? await Promise.all([
    supabase.rpc("list_member_directory_details", { p_organization_id: organizationId }),
    supabase.rpc("list_event_team", { p_organization_id: organizationId, p_event_id: eventId }),
    supabase.rpc("list_event_registrations", { p_organization_id: organizationId, p_event_id: eventId }),
  ]) : [{ data: [], error: null }, { data: [], error: null }, { data: [], error: null }];
  if (directoryResult.error || teamResult.error || registrationsResult.error) throw new Error("Failed to load event management data");
  const members = (directoryResult.data as Member[] | null) ?? []; const team = (teamResult.data as Team[] | null) ?? []; const registrations = (registrationsResult.data as Registration[] | null) ?? []; const currentRoster = registrations.filter((registration) => registration.registration_status === "registered");
  const editable = manager && event.season_status === "active" && event.status === "draft";
  const manageable = manager && event.season_status === "active" && ["draft", "published"].includes(event.status);
  const hasStarted = new Date(event.starts_at) <= new Date();
  const hasEnded = new Date(event.ends_at) <= new Date();

  return <main className="mx-auto flex min-h-screen w-full max-w-3xl flex-col gap-6 px-6 py-10">
    <Link className="text-sm text-zinc-600 underline" href={`/organizations/${organizationId}/events`}>كل الفعاليات</Link>
    <header><p className="text-sm font-semibold text-blue-700">{event.season_name}</p><div className="mt-2 flex flex-wrap items-center gap-2"><h1 className="text-3xl font-bold">{event.title}</h1><span className="rounded-full bg-zinc-100 px-2 py-1 text-xs">{labels[event.status]}</span></div><p className="mt-2 text-zinc-600">{formatDateTime(event.starts_at)} — {formatDateTime(event.ends_at)} · {event.venue || "مكان غير محدد"}</p></header>
    {query.error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{errors[String(query.error)] ?? "حدث خطأ. حاول مجددًا."}</p>}
    {query.success && <p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-700">{success[String(query.success)] ?? "تم الحفظ."}</p>}
    {(manager || event.my_team_role) && <section className="rounded-xl border border-zinc-200 p-5">{manager && event.objective && <><h2 className="font-semibold">الهدف</h2><p className="mt-2 whitespace-pre-wrap leading-7 text-zinc-700">{event.objective}</p></>}{manager && <><p className="mt-4 text-sm text-zinc-600">تسجيلات نشطة: {event.registration_count ?? 0}{event.capacity ? ` من ${event.capacity}` : ""}</p>{event.status === "published" && <Link className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-blue-700 underline" href={`/events/${eventId}`} target="_blank">فتح صفحة التسجيل العامة</Link>}</>}{!manager && event.my_team_role && <p className="text-sm font-semibold text-blue-700">دوري في الفريق: {event.my_team_role}</p>}</section>}

    {editable && <section className="rounded-xl border border-zinc-200 p-5"><details><summary className="flex min-h-11 cursor-pointer items-center font-semibold text-blue-700">تعديل المسودة</summary><form action={updateDraftEvent.bind(null, organizationId)} className="mt-4 grid gap-3"><input type="hidden" name="event_id" value={eventId} /><EventFields event={event} /><button className="min-h-11 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">حفظ التعديل</button></form></details><form action={publishEvent.bind(null, organizationId)} className="mt-3 border-t border-zinc-200 pt-3"><input type="hidden" name="event_id" value={eventId} /><button className="min-h-11 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">نشر الفعالية</button></form></section>}

    {manager && <section className="grid gap-4 rounded-xl border border-zinc-200 p-5"><div><h2 className="text-xl font-semibold">فريق الفعالية</h2><p className="mt-1 text-sm text-zinc-600">عضو نشط واحد له مسمى دور واحد داخل هذه الفعالية.</p></div>{manageable && <form action={assignEventTeamMember.bind(null, organizationId)} className="grid gap-3 border-t border-zinc-200 pt-4 sm:grid-cols-2"><input type="hidden" name="event_id" value={eventId} /><label className="grid gap-1 text-sm font-medium">العضو<select name="member_user_id" required defaultValue="" className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2"><option value="" disabled>اختر عضوًا</option>{members.map((member) => <option key={member.user_id} value={member.user_id}>{member.display_name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">مسمى الدور<input name="role_title" minLength={2} maxLength={120} required className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2" /></label><button className="min-h-11 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white sm:col-span-2">حفظ الفريق</button></form>}{team.length ? <ul className="grid gap-2">{team.map((member) => <li key={member.membership_id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-zinc-50 p-3"><span>{member.display_name} · {member.role_title}</span>{manageable && <form action={removeEventTeamMember.bind(null, organizationId)}><input type="hidden" name="event_id" value={eventId} /><input type="hidden" name="membership_id" value={member.membership_id} /><button className="min-h-11 text-sm font-semibold text-red-700 underline">إزالة</button></form>}</li>)}</ul> : <p className="text-sm text-zinc-600">لا يوجد فريق بعد.</p>}</section>}

    {manager && <section className="grid gap-4 rounded-xl border border-zinc-200 p-5"><div><h2 className="text-xl font-semibold">التسجيل والحضور</h2><p className="mt-1 text-sm text-zinc-600">القائمة النشطة الحالية: {currentRoster.length}. يلزم تحديد حالة كل مسجل عند الإتمام.</p></div>{registrations.length ? <ul className="grid gap-2">{registrations.map((registration) => <li key={registration.registration_id} className="rounded-lg bg-zinc-50 p-3 text-sm">{registration.display_name} · {labels[registration.registration_status] ?? registration.registration_status}</li>)}</ul> : <p className="text-sm text-zinc-600">لا توجد تسجيلات بعد.</p>}{event.status === "published" && event.season_status === "active" && (hasEnded ? <details className="border-t border-zinc-200 pt-3"><summary className="flex min-h-11 cursor-pointer items-center font-semibold text-blue-700">إتمام الفعالية وتسجيل الحضور</summary><form action={completeEvent.bind(null, organizationId)} className="mt-4 grid gap-3"><input type="hidden" name="event_id" value={eventId} />{currentRoster.map((registration) => <label key={registration.registration_id} className="grid gap-1 text-sm font-medium sm:grid-cols-2 sm:items-center"><span>{registration.display_name}</span><input type="hidden" name="registration_id" value={registration.registration_id} /><select name="attendance_status" required defaultValue="" className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2"><option value="" disabled>اختر الحضور</option><option value="attended">حضر</option><option value="absent">غاب</option></select></label>)}<button className="min-h-11 rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white">تأكيد الإتمام</button></form></details> : <p className="border-t border-zinc-200 pt-3 text-sm text-zinc-600">يتاح تسجيل الحضور بعد انتهاء الفعالية.</p>)}</section>}

    {manageable && !hasStarted && <section className="rounded-xl border border-red-200 p-5"><details><summary className="flex min-h-11 cursor-pointer items-center font-semibold text-red-700">إلغاء الفعالية</summary><p className="mt-2 text-sm text-zinc-600">الإلغاء نهائي داخل هذا الموسم. تبقى السجلات محفوظة.</p><form action={cancelEvent.bind(null, organizationId)} className="mt-3"><input type="hidden" name="event_id" value={eventId} /><button className="min-h-11 font-semibold text-red-700 underline">تأكيد الإلغاء</button></form></details></section>}
  </main>;
}

function EventFields({ event }: { event: Event }) {
  const min = inputDateTime(new Date().toISOString());
  return <><label className="grid gap-1 text-sm font-medium">العنوان<input name="title" defaultValue={event.title} minLength={2} maxLength={160} required className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2" /></label><label className="grid gap-1 text-sm font-medium">الهدف<textarea name="objective" defaultValue={event.objective ?? ""} minLength={2} maxLength={3000} rows={4} required className="rounded-lg border border-zinc-300 px-3 py-2" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">يبدأ<input type="datetime-local" name="starts_at" defaultValue={inputDateTime(event.starts_at)} min={min} required className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2" /></label><label className="grid gap-1 text-sm font-medium">ينتهي<input type="datetime-local" name="ends_at" defaultValue={inputDateTime(event.ends_at)} min={min} required className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2" /></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">المكان (اختياري)<input name="venue" defaultValue={event.venue ?? ""} maxLength={300} className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2" /></label><label className="grid gap-1 text-sm font-medium">السعة (اختياري)<input name="capacity" type="number" defaultValue={event.capacity ?? ""} min="1" max="100000" className="min-h-11 rounded-lg border border-zinc-300 px-3 py-2" /></label></div></>;
}
